### ISSUE TITLE
FR: Device switch

### ISSUE THREAD

**Issue by decatetsu** [Mocca101/obsidian-plugin-groups#2] opened 2022-12-22 18:25 UTC
It'd be cool to have the ability to choose a device for group (mobile/pc). It'll be very helpful to delay startup of a group of heavy plugins on mobile.

**Comment by imeed166** [comment] 2022-12-22 19:03
+1

**Comment by chrisgrieser** [comment] 2022-12-22 19:47
Not only mobile/desktop, but also work desktop and home desktop would make sense, since you are sometimes using slightly different setups in both

**Comment by Mocca101** [comment] 2022-12-22 21:30
Good idea! I'll look into it

**Comment by Lisandra-dev** [comment] 2022-12-23 15:15
If I can help, for Group snippets, I just "simply" detect the platform (for example "mobile") using `const platform = Platform.isDesktop ? 'desktop' : 'mobile'`
I, after, activate the snippets if the **group name** contains the word `mobile` or `desktop`. If the group doesn't contain the word, then it's both. 

On another hand, with my fast-start user plugin snippets, I used that : 
```js
if (!plugin.app.isMobile) { 
	// run here the desktop group
} else {
	// run here the mobile group 
}
```

For the "differenciate between work desktop" and "Home desktop", I dunno how to detect these change, but the API allow to get a lot of information, so maybe we can detect IOS/Android/IpadOS/IOS/Mac/Linux and base the change on that ? 

To be honest, I'm curious how can we differentiate two computer running the same OS.

**Comment by Mocca101** [comment] 2022-12-24 11:09
Thanks for the advice! The way I'm approaching it now is through letting users create device names, and then setting the current device by Saving the name to the local storage (probably per vault, but I'm open for input wether it should be per vault & device or just per device). Thanks to Licat for pointing me in that direction!

**Comment by Lisandra-dev** [comment] 2022-12-24 11:14
Oh, I dunno it was possible! But, yes, good idea :D

**Comment by Mocca101** [comment] 2022-12-26 22:16
There's now a new release available with BRAT, please let me know if this works the way you imagened it to or not. And of course if you encounter any bugs/unexpected behaviour.

**Comment by decatetsu** [comment] 2022-12-27 08:52
Tested on my phone, loading time was reduced to 3 seconds instead of 7! I excluded all plugins except plugin groups inside `community-plugins.json` and have no issues with functionality. But I'll continue testing. Thanks!

**Comment by Mocca101** [comment] 2022-12-27 15:12
Really happy to hear that!

**Comment by Mocca101** [comment] 2022-12-30 09:15
As there seem to be no issues I'll close this issue for now.

**Closed by Mocca101** 2022-12-30 09:15 UTC
Labels: enhancement, Doing
